export const IMPACT_REASONING: Record<string, string[]> = {
  "geopolitical": [
    "War outbreak → immediate crash in equities; oil, gold, defense stocks surge. Safe-haven flight to USD, Yen, CHF.",
    "Ceasefire / peace deal → sharp relief rally, especially in affected-region stocks and energy.",
    "Territorial sanctions imposed → targeted country's market plunges; global supply-chain stocks fall.",
    "Military coup in resource-rich nation → commodity spike; EM index sell-off.",
    "Nuclear threat escalation → global panic sell, bond yields drop as capital flees to safety.",
  ],
  "central-bank": [
    "Unexpected rate hike → broad equity sell-off, especially growth/tech; bank stocks rise short-term.",
    "Surprise rate cut → stocks rally sharply; bond prices rise; USD weakens.",
    "CPI/PPI higher than expected → sell-off in rate-sensitive sectors; real assets and commodities gain.",
    "GDP contraction/recession signal → broad market fall; defensive sectors (utilities, healthcare) outperform.",
    "PMI collapse below 50 → manufacturing and industrial stocks fall; recession pricing begins.",
  ],
  "crisis": [
    "Bank bankruptcy / bailout → financial sector free-fall; credit markets seize up; contagion spreads to regional banks.",
    "Sovereign debt default → bond yield spike for that nation; EM debt sell-off; flight to US Treasuries.",
    "Liquidity crunch in money markets → interbank lending freezes; repo rates spike; central bank emergency intervention.",
    "Systemic collapse of major institution → 2008-style panic; margin calls cascade; broad market circuit breakers.",
    "Credit rating downgrade to junk → forced selling by pension funds; borrowing costs surge; currency depreciates.",
  ],
  "pandemic": [
    "New health emergency declared → travel, hospitality, retail stocks crash; pharma and biotech rally.",
    "Lockdown imposed → supply chains break; e-commerce, remote work stocks gain; physical retail craters.",
    "Vaccine breakthrough announced → reopening trades surge (airlines, hotels); stay-at-home stocks correct.",
    "Hospitalization rate spikes → healthcare systems strained; insurance stocks fall; medical supply stocks rally.",
    "Pandemic fiscal stimulus → government debt surges; inflation fears rise; gold and Bitcoin benefit.",
  ],
  "energy": [
    "Oil supply disruption → crude spikes; energy stocks rally; airline/transport stocks sell off.",
    "OPEC+ production cut announced → oil prices surge; energy sector outperforms broadly.",
    "Natural gas shortage → utility stocks volatile; fertilizer and industrial input costs rise.",
    "Renewable energy policy shift → solar, wind, EV stocks move sharply; fossil fuel stocks re-price.",
    "Strategic petroleum reserve release → oil dips short-term; energy stocks see profit-taking.",
  ],
  "trade": [
    "New tariff imposed → impacted sector stocks fall; domestic producers may benefit short-term.",
    "Trade deal signed → export-heavy stocks rally; tariffs removed; supply-chain confidence returns.",
    "Trade war escalation → global growth fears rise; manufacturing PMIs fall; safe-haven currencies strengthen.",
    "Export ban on critical goods → reliant industries scramble; prices of banned goods spike globally.",
    "WTO ruling against trade practice → targeted country's export sector drops; currency weakens.",
  ],
  "election": [
    "Pro-business candidate wins → equity rally; financial, energy, defense sectors gain; volatility drops.",
    "Tax hike / regulation-focused winner → healthcare, tech, energy fall; renewable and infrastructure gain.",
    "Hung parliament / coalition gridlock → policy paralysis; markets drift; uncertainty premium rises.",
    "Landslide victory → swift policy execution expected; sector rotates based on winning party agenda.",
    "Election dispute / contested result → volatility spikes; currency and bonds see safe-haven flows.",
  ],
  "currency": [
    "Currency peg collapse → extreme FX volatility; import-heavy stocks crash; exporters rally.",
    "Central bank FX intervention → short-term currency stabilisation; reserves drain if unsustainable.",
    "Reserve currency status shift → gradual USD weakening; gold, EM currencies benefit over time.",
    "Currency devaluation → exports become competitive; inflation imports rise; foreign debt burden swells.",
    "Digital currency / stablecoin regulation → crypto prices move sharply; fintech stocks affected.",
  ],
  "corporate": [
    "Major earnings beat → stock gaps up; sector peers rally on sympathy; options volatility crushes.",
    "Accounting fraud exposed → stock crashes 30-50%; auditor and board face lawsuits; sector confidence shaken.",
    "CEO abruptly resigns → uncertainty spike; stock drops 5-15% until succession clarity emerges.",
    "Activist investor takes stake → stock rallies on break-up / buyback hope; management under pressure.",
    "Massive share buyback announced → EPS boosts; stock price support; debt-funded buybacks raise risk flags.",
  ],
  "tech": [
    "AI breakthrough announced → leader stocks gap up; entire AI sector re-rates; compute hardware stocks benefit.",
    "Major chip supply disruption → semiconductor stocks fall; downstream tech hardware impacted.",
    "Regulatory antitrust action → big tech sells off; smaller competitors may gain on level playing field.",
    "Quantum computing milestone → long-duration tech rallies; encryption-dependent sectors re-price risk.",
    "Tech IPO / mega-deal announced → sector attention increases; comparable private companies re-value.",
  ],
  "climate": [
    "Category 5 hurricane makes landfall → insurance stocks plummet; home improvement retailers rally.",
    "Wildfire destroys urban area → property insurers hit; construction materials and HVAC stocks gain.",
    "Government net-zero mandate → renewable energy stocks soar; oil and gas majors reprice downward.",
    "Extreme flood disrupts manufacturing → supply-chain dependent stocks fall; logistics and freight impacted.",
    "Carbon tax / emissions policy enacted → high-emission sectors (steel, cement, airlines) drop; carbon credit markets surge.",
  ],
}
